from django.conf.urls import *
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from preventivos import views
from preventivos import forms
from preventivos.forms import *
from preventivos.views import *
from django.conf import settings

FORMS = [("nro", PrimerForm),
     ("actores", SegundoForm),    ("autoridades", TerceroForm),     ("confirmation", FinForm),
    ]

contact_wizard = preventivos.as_view(FORMS)

handler404 = 'preventivos.views.page_not_found'
handler500 = 'preventivos.views.server_error'

admin.autodiscover()

urlpatterns = [
  	url(r'^user/$',new_user),
    url(r'^user/create/$',user_create),
   #url(r'^permgroups/$',permisos'),
    url(r'^climas/$', climas),
    url(r'^climas/(?P<idcli>[0-9A-Za-z]+)/$',nclimas),
    url(r'^hogares/$',hogares),
    url(r'^hogares/(?P<idipv>[0-9A-Za-z]+)/$', nhogares),
    url(r'^lugares/$', lugares),
    url(r'^lugares/(?P<idlugar>[0-9A-Za-z]+)/$', nlugares),
    url(r'^ciudades/$',ciudades),
    url(r'^addciudades/$',ciudadesadd),
    url(r'^seleccionar/hechos/tdelito/(?P<idtd>[0-9A-Za-z]+)/$', obtener_delitos),
    url(r'^seleccionar/hechos/delito/(?P<idd>[0-9A-Za-z]+)/$', obtener_modos),
    url(r'^new/first/tdelito/(?P<idtd>[0-9A-Za-z]+)/$', obtener_delitos),
    url(r'^new/first/delito/(?P<idd>[0-9A-Za-z]+)/$', obtener_modos),
    url(r'^actuantes/ure/(?P<ure>[0-9A-Za-z]+)/$', obtener_dependencias),
    url(r'^ure/(?P<ure>[0-9A-Za-z]+)/$', obtener_dependencias),
    url(r'^user/ure/(?P<ure>[0-9A-Za-z]+)/$', obtener_dependencias),
    url(r'^ciudades/(?P<pais>[0-9A-Za-z]+)/$', obtener_provincia),
    url(r'^ciudades/editar/(?P<idciu>[0-9A-Za-z]+)/$', ciudad),
    url(r'^ciudades/dpto/(?P<prvi>[0-9A-Za-z]+)/$', obtener_departa),
    url(r'^paises/$', pais),
    url(r'^newpais/$', npais),
    url(r'^newtipodelito/$', ntipodelito),
    url(r'^provincias/$', provincias),
    url(r'^departamentos/$',departamentos),
    url(r'^paises/(?P<idlista>[0-9A-Za-z]+)/$', paise),
    url(r'^provincias/(?P<idpcia>[0-9A-Za-z]+)/$', provi),
    url(r'^departamentos/(?P<iddepto>[0-9A-Za-z]+)/$', depto),
    url(r'^unidades/$', unidades),
    url(r'^unidades/(?P<idUnidad>[0-9A-Za-z]+)/$', unidad),
    url(r'^dependencias/$',dependencias),
    url(r'^dependencias/(?P<idDepe>[0-9A-Za-z]+)/$', dependencia),
    url(r'^peopleenv/$',personasi),
    url(r'^peopleenv/(?P<idple>[0-9A-Za-z]+)/$', npersonasi),
    url(r'^typedelitos/$', tipodelitos),
    url(r'^typedelitos/(?P<idtipo>[0-9A-Za-z]+)/$', tipodelito),
    url(r'^reportes/(?P<idtd>[0-9A-Za-z]+)/$', obtener_delitos),
    #url(r'^expodata/$', repsurbana,name='repsurbana'),
    url(r'^delitos/$', delitos),
    url(r'^delitos/(?P<idelito>[0-9A-Za-z]+)/$', delito),
    url(r'^modus/$', modus),
    url(r'^modus/(?P<idmod>[0-9A-Za-z]+)/$', modos),
    url(r'^jobs/$', jobs),
    url(r'^jobs/(?P<idjob>[0-9A-Za-z]+)/$', jobselected),
    url(r'^trademark/$', marcas),
    url(r'^trademark/(?P<idmars>[0-9A-Za-z]+)/$', tradeselec),
    url(r'^typearms/$', tiposarmas),
    url(r'^typearms/(?P<idta>[0-9A-Za-z]+)/$', tiposaselec),
    url(r'^subarms/$', subtiposarms),
    url(r'^subarms/(?P<idsta>[0-9A-Za-z]+)/$', subaselect),
    url(r'^newtypearms/$', ntypesa),
    url(r'^items/$', rubros),
    url(r'^items/(?P<idrub>[0-9A-Za-z]+)/$', itemselec),
    url(r'^category/$', categorias),
    url(r'^category/(?P<idcat>[0-9A-Za-z]+)/$', catselect),
    url(r'^newrubro/$', nrubros),
    url(r'^barrios/$', barrios),
    url(r'^addbarrios/$', addbarrios),
    url(r'^barrios/(?P<idbar>[0-9A-Za-z]+)/$', nbarrios),
    url(r'^helpass/$', helpassword),
    #url(r'^barrios/ids/(?P<idci>[0-9A-Za-z]+)/$', obtener_calles'),
    url(r'^address/$', calles),
    url(r'^address/(?P<idadrs>[0-9A-Za-z]+)/$', ncalles),
    url(r'^addcalles/$', addcalles),
    url(r'^authorities/$',autoridades),
    url(r'^authorities/(?P<idaut>[0-9A-Za-z]+)/$',autoridad),
    url(r'^actuantes/$', actuantes),
    url(r'^actuantes/(?P<idact>[0-9A-Za-z]+)/$',oficiales),
    #url(r'^user/new/$','preventivos.views.new_user'),
    url(r'^groupusers/$', grupos),
    url(r'^groupfree/$', gruposperm),
    url(r'^newgroup/$', ngrupos),
    url(r'^groupusers/(?P<idgr>[0-9A-Za-z]+)/$',grupusers),
    url(r'^persona/$', personas),
    url(r'^newpersona/$', newperso),
    url(r'^persona/ver/(?P<idper>[0-9A-Za-z]+)/$',persona),
    url(r'^persona/(?P<pais>[0-9A-Za-z]+)/$',obtener_ciudades),
    url(r'^new/$', contact_wizard, name='contact_wizard'),
    url(r'^persona/town/(?P<idcit>[0-9A-Za-z]+)/$',obtener_barrios),
    url(r'^personavif/town/(?P<idcit>[0-9A-Za-z]+)/$',obtener_barrios),
    url(r'^persona/street/(?P<idcit>[0-9A-Za-z]+)/$',obtener_calle),
     url(r'^personavif/street/(?P<idcit>[0-9A-Za-z]+)/$',obtener_calle),
    url(r'^controller/$', control),
    url(r'^seleccionar/(?P<prev>[0-9A-Za-z]+)/$',selectPrev),
    url(r'^controller/(?P<user>[0-9A-Za-z]+)/$', reporactivity,name='reporactivity'),
    url(r'^seleccionar/informa/(?P<idhec>[0-9A-Za-z]+)/(?P<idprev>[0-9A-Za-z]+)/(?P<aforo>[0-9A-Za-z]+)/$', informe,name='informa'),
    url(r'^autorizar/(?P<idprev>[0-9A-Za-z]+)/$',autorizar,name='autorizar'),
    url(r'^user/edit/$',user_edit,name="user_edit"),
    url(r'^user/edit/destino/(?P<usuario>[0-9A-Za-z]+)/$',user_edit_destino,name="user_edit_destino"),
    url(r'^user/edit/save/destino/(?P<usuario>[0-9A-Za-z]+)/$',user_edit_save_destino,name="user_edit_save_destino"),
    url(r'^user/edit/actuante/(?P<usuario>[0-9A-Za-z]+)/$',user_edit_actuante,name="user_edit_actuante"),
    url(r'^new/first/(?P<idprev>[0-9A-Za-z]+)/$',obtener_datosfirst,name="newhecho"),
    url(r'^seleccionar/(?P<prev>[0-9A-Za-z]+)/$',selectPrev,name='selectPrev'),
    url(r'^seleccionar/hechos/(?P<idprev>[0-9A-Za-z]+)/$',updatehechos,name='updatehechos'),
    url(r'^seleccionar/hechos/pdfs/(?P<idprev>[0-9A-Za-z]+)/$',pdfs,name='reportes'),
    url(r'^persona/modif@/(?P<idhec>[0-9A-Za-z]+)/(?P<idper>[0-9A-Za-z]+)/$',persinvom,name='persinvoluc'),
    url(r'^persona/(?P<idhec>[0-9A-Za-z]+)/(?P<idper>[0-9A-Za-z]+)/$',persinvo,name='persinvol'),
    url(r'^peoplein/(?P<idper>[0-9A-Za-z]+)/$',verpersin,name='verpersin'),
    #url(r'^topdf/$','to_pdf',name= "to_pdf"),
    url(r'^lugar_hecho/(?P<idhecho>[0-9A-Za-z]+)/(?P<idprev>[0-9A-Za-z]+)/$',lugar_hecho,name='lugar_hecho'),
    url(r'^elementos/(?P<idhecho>[0-9A-Za-z]+)/$', elementos,name='elementos'),
    url(r'^elemento/(?P<idhecho>[0-9A-Za-z]+)/(?P<elemento>[0-9A-Za-z]+)/$', elemento,name='elemento'),
    url(r'^getcategory/(?P<rubro>[0-9A-Za-z]+)/$', get_categories,name='get_category'),
    url(r'^mapsanality/$', seemaps,name='seemaps'),
    url(r'^hechos/$', rephechos,name='rephechos'),
    url(r'^automotores/$', repautos,name='repautos'),
    url(r'^homicides/$', killings,name='killings'),
    url(r'^forages/$', repforages,name='repforages'),
    url(r'^ciudades_ajax/',ciudades_ajax,name='ciudades_ajax'),
    url(r'^ciudades_ajax_provincia/(?P<id>[0-9A-Za-z]+)/$',ciudades_ajax_provincia,name='ciudades_ajax_provincia'),
    url(r'^usuarios_ajax/',usuarios_ajax,name='usuarios_ajax'),
    url(r'^paises_ajax/',paises_ajax,name='paises_ajax'),
    url(r'^buscar_usuario/(?P<id>[0-9A-Za-z]+)/$',buscar_usuario,name='buscar_usuario'),
    url(r'^ampliacion/(?P<idprev>[0-9A-Za-z]+)/$', ampliacion,name='ampliacion'),
    url(r'^ampliacion/(?P<idprev>[0-9A-Za-z]+)/(?P<idamp>[0-9A-Za-z]+)/$', ver_ampliacion,name='ver_ampliacion'),
    url(r'^amplielem/(?P<idprev>[0-9A-Za-z]+)/(?P<idamp>[0-9A-Za-z]+)/$', amplia_ele,name='amplia_ele'),
    url(r'^reporampli/(?P<idprev>[0-9A-Za-z]+)/(?P<idamp>[0-9A-Za-z]+)/$', reporampli,name='reporampli'),
     url(r'^eleampli/(?P<idhecho>[0-9A-Za-z]+)/(?P<elemento>[0-9A-Za-z]+)/(?P<idamp>[0-9A-Za-z]+)/$', eleampli,name='eleampli'),
     url(r'^amplipers/(?P<idprev>[0-9A-Za-z]+)/(?P<idamp>[0-9A-Za-z]+)/$', amplia_pers,name='amplia_pers'),
    url(r'^amplipers/(?P<idprev>[0-9A-Za-z]+)/(?P<idamp>[0-9A-Za-z]+)/(?P<idper>[0-9A-Za-z]+)/$', amplia_per,name='amplia_per'),
    url(r'^finalizar/(?P<idprev>[0-9A-Za-z]+)/(?P<idamp>[0-9A-Za-z]+)/$', finalizar,name='finalizar'),
    url(r'^enviar/(?P<idprev>[0-9A-Za-z]+)/(?P<idamp>[0-9A-Za-z]+)/$', enviar,name='enviar'),
    url(r'^verificardni/(?P<tdni>[0-9]+)/(?P<dni>[0-9]+)/$',verificardni,name='verificardni'),
    url(r'^modouso/(?P<uso>[0-9A-Za-z]+)/$', obtener_subtiposa),
    url(r'^seedata/$', verprev),
    url(r'^seeampli/$', verampli),
    url(r'^seehechos/$', verhechos),
    url(r'^seedelitos/$', verdelitos),
    url(r'^seedelitos/(?P<idtd>[0-9A-Za-z]+)/$', obtener_delitos),
    url(r'^peoplein/$', verperin),
    url(r'^objectsin/$', verobjin),
    #url(r'^vfliar/(?P<idhec>[0-9A-Za-z]+)/$', violencia,name='formvif'),
    #url(r'^personavif/(?P<idhec>[0-9A-Za-z]+)/(?P<idper>[0-9A-Za-z]+)/$', persinvovif,name='persinvolvif'),
    #url(r'^webservice/$', sendfechas'),
    url(r'^pwebservice/$', enviadop,name='pwebservice'),
    url(r'^pwebservice/enviar/(?P<idprev>[0-9]+)/$', enviarp,name='enviarws'),
    url(r'^awebservice/$', enviadoa,name='awebservice'),
    url(r'^pendientes_envio/$',pendientes_envio,name='pendientes_envio'),
    url(r'^pendientes_autorizacion/$',pendientes_autorizacion,name='pendientes_autorizacion'),
    url(r'^cambiar_password/$',cambiar_password,name='cambiar_password'),
    url(r'^autorizados_reenvio/(?P<dependencia>[0-9]+)/$',preventivos_autorizados_n_dias,name='autorizados_reenvio'),
    url(r'^autorizados_envio/$',autorizados_envio,name='autorizados_envio'),
    url(r'^envio/(?P<idprev>[0-9A-Za-z]+)/$',envio,name='envio'),
    url(r'^reenvio/$',reenvio,name='reenvio'),
    url(r'^reenviar/(?P<idprev>[0-9A-Za-z]+)/$',reenviar,name='reenviar'),
    url(r'^verificar_persona/(?P<dni>[0-9]+)/$',verificar_persona,name='verificar_persona'),
    url(r'^estados_civiles/$',estados_civiles,name='estados_civiles'),
    url(r'^dependencias_ajax/$',dependencias_ajax,name='dependencias_ajax'),
    url(r'^jerarquias_ajax/$',jerarquias_ajax,name='jerarquias_ajax'),
    url(r'^user_create_save/$',user_create_save,name='user_create_save'),
    url(r'^user/reenviar_mail/(?P<usuario>[0-9]+)/$',user_reenviar_mail, name='reenviar_mail'),
    url(r'^user/modificar_mail/(?P<usuario>[0-9]+)/$',user_modificar_mail, name='modificar_mail'),
    url(r'^user/activar/(?P<usuario>[0-9]+)/$',user_activar,name='user_activar'),
    url(r'^user/roles/(?P<usuario>[0-9]+)/$',user_roles,name='user_roles'),
    url(r'^user/roles_save/$',user_roles_save,name='user_roles_save'),
    url(r'^obtener_preventivo/(?P<depe>[0-9]+)/(?P<numero>[0-9]+)/(?P<anio>[0-9]+)/$',obtener_preventivo,name='obtener_preventivo'),
    url(r'^inicio/$',inicio,name='inicio'),
    url(r'^', page_not_found),
    url(r'^', server_error),
   ]
