# Generated by Django 2.0.2 on 2018-11-08 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import prontuario.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('preventivos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreventivosPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preventivo_id', models.IntegerField()),
                ('preventivo_nro', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('dependencia_id', models.IntegerField()),
                ('dependencia', models.CharField(max_length=80)),
                ('persona_id', models.IntegerField()),
                ('documento', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=150)),
                ('rol_id', models.IntegerField()),
                ('rol', models.CharField(max_length=150)),
                ('hecho_id', models.IntegerField()),
                ('hecho_descripcion', models.CharField(blank=True, max_length=2000)),
            ],
            options={
                'managed': False,
                'db_table': 'preventivos_persona',
            },
        ),
        migrations.CreateModel(
            name='CivilStatuses',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'civil_statuses',
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='FotosPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_foto', models.CharField(max_length=25)),
                ('foto', models.ImageField(upload_to=prontuario.models.upload_name)),
                ('fecha', models.DateField(auto_now=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fotos_persona', to='preventivos.Personas')),
            ],
            options={
                'db_table': 'fotos_persona',
            },
        ),
        migrations.CreateModel(
            name='Identificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_identificacion', models.DateField()),
                ('prontuario_local', models.CharField(max_length=7)),
                ('altura_metros', models.IntegerField()),
                ('altura_centimetros', models.IntegerField()),
                ('cutis', models.CharField(max_length=25)),
                ('cabello_color', models.CharField(max_length=25)),
                ('es_tenido', models.BooleanField(default=False)),
                ('posee_tatuajes', models.BooleanField(default=False)),
                ('posee_cicatrices', models.BooleanField(default=False)),
                ('observaciones', models.CharField(max_length=250)),
            ],
            options={
                'get_latest_by': 'id',
                'db_table': 'identificacion',
            },
        ),
        migrations.CreateModel(
            name='Indice',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=20)),
                ('n_c', models.CharField(blank=True, max_length=100)),
                ('fechan', models.CharField(max_length=100)),
                ('tipo_p', models.CharField(max_length=25)),
                ('n_p', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('fechase', models.CharField(max_length=100)),
                ('ob', models.CharField(max_length=500)),
                ('fechac', models.CharField(max_length=20)),
                ('tipo', models.CharField(blank=True, max_length=150)),
                ('nombre_archivo', models.CharField(blank=True, max_length=255)),
                ('identificado', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'indice',
            },
        ),
        migrations.CreateModel(
            name='Nationalities',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'nationalities',
            },
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro', models.CharField(max_length=7, unique=True)),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True)),
                ('fotos', models.ManyToManyField(blank=True, related_name='fotos', to='prontuario.FotosPersona')),
                ('identificaciones', models.ManyToManyField(to='prontuario.Identificacion')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='preventivos.Personas')),
            ],
            options={
                'db_table': 'prontuario',
            },
        ),
        migrations.CreateModel(
            name='ProntuarioLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prontuario_log',
            },
        ),
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='prontuario.Countries')),
            ],
            options={
                'db_table': 'provinces',
            },
        ),
        migrations.CreateModel(
            name='RecordIdentifications',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('criminal_record_nro', models.BigIntegerField(unique=True)),
                ('dni', models.CharField(blank=True, max_length=15)),
                ('name_1', models.CharField(max_length=50)),
                ('name_2', models.CharField(blank=True, max_length=50)),
                ('surname', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('instructed', models.BooleanField(default=None)),
                ('e_mail', models.CharField(blank=True, max_length=60)),
                ('telephone_number', models.CharField(blank=True, max_length=20)),
                ('alias', models.CharField(blank=True, max_length=20)),
                ('place_of_birth', models.CharField(max_length=100)),
                ('address_city', models.CharField(blank=True, max_length=100)),
                ('address_street', models.CharField(blank=True, max_length=100)),
                ('foreign_address', models.CharField(blank=True, max_length=100)),
                ('father_surname', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('father_dni', models.CharField(blank=True, max_length=15)),
                ('mother_surname', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_dni', models.CharField(blank=True, max_length=15)),
                ('reason_for_the_identification', models.CharField(max_length=256)),
                ('jurisdiction_id', models.IntegerField()),
                ('user_create', models.IntegerField()),
                ('user_update', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('sex', models.CharField(max_length=10)),
                ('civil_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='prontuario.CivilStatuses')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='prontuario.Nationalities')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='prontuario.Provinces')),
            ],
            options={
                'db_table': 'record_identifications',
            },
        ),
        migrations.CreateModel(
            name='RefCiudadesRh',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
                ('pais_id', models.IntegerField()),
                ('provincia_id', models.IntegerField(blank=True, null=True)),
                ('cp', models.CharField(blank=True, max_length=45)),
            ],
            options={
                'db_table': 'ref_ciudades',
            },
        ),
        migrations.CreateModel(
            name='RefContextura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'db_table': 'ref_contextura',
            },
        ),
        migrations.CreateModel(
            name='RefEstadoCivilRh',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'ref_estado_civil',
            },
        ),
        migrations.CreateModel(
            name='RefGrupoSanguineoRh',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'ref_grupo_sanguineo',
            },
        ),
        migrations.CreateModel(
            name='RefOcupacionEspecifica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'ref_ocupacion_especifica',
            },
        ),
        migrations.CreateModel(
            name='RefPaisesRh',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
                ('nacionalidad', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'ref_paises',
            },
        ),
        migrations.CreateModel(
            name='RefProvinciaRh',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
                ('pais_id', models.IntegerField()),
            ],
            options={
                'db_table': 'ref_provincia',
            },
        ),
        migrations.CreateModel(
            name='RefSexoRh',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'ref_sexo',
            },
        ),
        migrations.CreateModel(
            name='RefTipoCabello',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'ref_tipo_cabello',
            },
        ),
        migrations.CreateModel(
            name='RefTipoDocumentoRh',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'ref_tipo_documento',
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busqueda', models.CharField(blank=True, max_length=300, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historial_busqueda',
            },
        ),
        migrations.CreateModel(
            name='SearchResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_busqueda', models.IntegerField()),
                ('id_spid', models.IntegerField(blank=True, null=True)),
                ('id_rrhh', models.IntegerField(blank=True, null=True)),
                ('id_acei', models.IntegerField(blank=True, null=True)),
                ('id_prontuario', models.IntegerField(blank=True, null=True)),
                ('es_policia', models.BooleanField(default=False)),
                ('apellido_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('documento', models.CharField(blank=True, max_length=20, null=True)),
                ('ciudad_nacimiento', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad_nacimiento_id', models.IntegerField(blank=True, null=True)),
                ('ciudad_residencia', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad_residencia_id', models.IntegerField(blank=True, null=True)),
                ('pais_nacimiento', models.CharField(blank=True, max_length=50, null=True)),
                ('pais_nacimiento_id', models.IntegerField(blank=True, null=True)),
                ('fecha_nacimiento', models.CharField(blank=True, max_length=12, null=True)),
                ('alias', models.CharField(blank=True, max_length=50, null=True)),
                ('prontuario_acei', models.CharField(blank=True, max_length=30, null=True)),
                ('prontuario_spid', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_hora_creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resultados_busqueda',
            },
        ),
        migrations.CreateModel(
            name='TypeDnis',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'type_dnis',
            },
        ),
        migrations.CreateModel(
            name='Verificar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('verificado', models.BooleanField(default=False)),
                ('verificado_dia', models.DateField(null=True)),
                ('identificacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='prontuario.Identificacion')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='preventivos.Personas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('verifica_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_verifica', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prontuario_verificar',
            },
        ),
        migrations.AddField(
            model_name='recordidentifications',
            name='type_dni',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='prontuario.TypeDnis'),
        ),
        migrations.AddField(
            model_name='identificacion',
            name='cabello_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='prontuario.RefTipoCabello'),
        ),
        migrations.AddField(
            model_name='identificacion',
            name='contextura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='prontuario.RefContextura'),
        ),
        migrations.AddField(
            model_name='identificacion',
            name='dependencia_identificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='preventivos.Dependencias'),
        ),
        migrations.AddField(
            model_name='identificacion',
            name='ocupacion_especifica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='prontuario.RefOcupacionEspecifica'),
        ),
        migrations.AddField(
            model_name='identificacion',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='preventivos.Personas'),
        ),
    ]
