# Generated by Django 2.0.2 on 2018-11-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prontuariolog',
            name='accion',
            field=models.CharField(max_length=150),
        ),
    ]
