# Generated by Django 2.0.2 on 2018-12-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0002_auto_20181108_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prontuario',
            options={'permissions': (('can_change_prontuario_nro', 'Can change prontuario nro'),)},
        ),
        migrations.AlterField(
            model_name='prontuariolog',
            name='accion',
            field=models.CharField(max_length=300),
        ),
    ]
