# Generated by Django 2.0.2 on 2018-12-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0003_auto_20181205_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='prontuariolog',
            name='entidad',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prontuariolog',
            name='entidad_id',
            field=models.IntegerField(default=None),
        ),
    ]
