# Generated by Django 2.0.2 on 2018-12-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0004_actualizacion_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prontuariolog',
            name='entidad',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prontuariolog',
            name='entidad_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
