# Generated by Django 2.0.2 on 2019-01-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0006_prontuariolog_accion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prontuario',
            name='nro',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
