# Generated by Django 2.0.2 on 2019-02-07 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prontuario', '0007_auto_20190123_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepuracionProcesales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicita', models.DateField(auto_now_add=True)),
                ('id_registro', models.IntegerField()),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('causa_baja', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_baja', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_baja', to=settings.AUTH_USER_MODEL)),
                ('usuario_solicita', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_solicita', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'depuracion_procesales',
            },
        ),
    ]
