# Generated by Django 2.0.2 on 2019-02-07 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0008_add_depuracion_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depuracionprocesales',
            name='usuario_baja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_baja', to=settings.AUTH_USER_MODEL),
        ),
    ]
