# Generated by Django 2.0.2 on 2019-02-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0009_add_null_usuario_baja'),
    ]

    operations = [
        migrations.AddField(
            model_name='indice',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
    ]
