# Generated by Django 2.0.2 on 2019-02-11 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0010_add_borrado_field_Indice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indice',
            options={'permissions': (('can_set_deletable_prontuario', 'Can set deletable prontuario'),)},
        ),
    ]
