# Generated by Django 2.0.2 on 2019-02-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0011_add_delete_perm_Indice'),
    ]

    operations = [
        migrations.AddField(
            model_name='depuracionprocesales',
            name='nombre',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depuracionprocesales',
            name='numero_prontuario',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
