# Generated by Django 2.0.2 on 2019-03-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0012_add_fields_to_depuracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depuracionprocesales',
            name='id_registro',
            field=models.IntegerField(unique=True),
        ),
    ]
