# Generated by Django 2.0.2 on 2018-12-06 14:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actuantes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('funcion', models.IntegerField()),
                ('documento', models.IntegerField(unique=True)),
                ('apeynombres', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'actuantes',
                'ordering': ['documento'],
            },
        ),
        migrations.CreateModel(
            name='Ampliacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=2000)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('cierre_causa', models.BooleanField(default=False)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('fin_edicion', models.BooleanField(default=False)),
                ('sendwebservice', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ampliacion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Armas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('calibre', models.CharField(blank=True, max_length=10, null=True)),
                ('nro_arma', models.CharField(blank=True, max_length=50, null=True)),
                ('nro_doc', models.IntegerField(blank=True, null=True)),
                ('propietario', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_carga', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'armas',
                'ordering': ['tipos', 'subtipos', 'marcas'],
            },
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('idBarrio', models.AutoField(primary_key=True, serialize=False)),
                ('idLocalidad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'barrio',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Calles',
            fields=[
                ('idCalle', models.AutoField(primary_key=True, serialize=False)),
                ('idLocalidad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'calles',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='CambiarContrasenia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=20)),
                ('detalle_motivo', models.CharField(max_length=100)),
                ('usuario_que_cambia', models.CharField(max_length=12)),
                ('usuario', models.CharField(max_length=12)),
                ('fecha_cambio', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reset_passwords',
            },
        ),
        migrations.CreateModel(
            name='Comisarias',
            fields=[
                ('idorganismo', models.AutoField(primary_key=True, serialize=False)),
                ('idLocalidad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'comisarias',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Dependencias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'dependencias',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Detenidos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechahoradetencion', models.DateTimeField(blank=True, null=True)),
                ('fechahoralibertad', models.DateTimeField(blank=True, null=True)),
                ('libertad', models.CharField(blank=True, max_length=1, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=800, null=True)),
                ('borrado', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'detenidos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Domicilios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura', models.CharField(blank=True, default='0', max_length=4)),
                ('fecha_desde', models.DateField(blank=True, null=True)),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
                ('departamento', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('piso', models.CharField(blank=True, default='0', max_length=4)),
                ('lote', models.CharField(blank=True, default='0', max_length=4)),
                ('sector', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('manzana', models.CharField(blank=True, default='0', max_length=4)),
                ('calle2', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'domicilios',
                'get_latest_by': 'id',
                'ordering': ['-fecha_desde'],
            },
        ),
        migrations.CreateModel(
            name='Drogas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_carga', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'drogas',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Elementos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('borrado', models.CharField(blank=True, max_length=1, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=800, null=True)),
                ('cargado_prev', models.BooleanField(default=False)),
                ('ampliacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='preventivos.Ampliacion')),
            ],
            options={
                'db_table': 'elementos',
                'ordering': ['tipo', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Elementosarmas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idarma', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='preventivos.Armas')),
                ('idelemento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='relelem', to='preventivos.Elementos')),
            ],
            options={
                'db_table': 'elementosarmas',
                'ordering': ['idelemento'],
            },
        ),
        migrations.CreateModel(
            name='Elementoscars',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idelemento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='preventivos.Elementos')),
            ],
            options={
                'db_table': 'elementoscars',
            },
        ),
        migrations.CreateModel(
            name='Elementosdrogas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('droga', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='preventivos.Drogas')),
                ('idelemento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='preventivos.Elementos')),
            ],
        ),
        migrations.CreateModel(
            name='EnvioAmpJudicial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_envio', models.DateTimeField(auto_now=True)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('enviado', models.IntegerField(default=0)),
                ('ampliacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='preventivos.Ampliacion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'envioampjudicial',
                'ordering': ['fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='EnvioPreJudicial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_autorizacion', models.DateTimeField(null=True)),
                ('fecha_envio', models.DateTimeField(auto_now=True)),
                ('enviado', models.IntegerField(default=0)),
                ('dependencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='preventivos.Dependencias')),
            ],
            options={
                'db_table': 'envioprejudicial',
                'ordering': ['fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Errores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'errores',
            },
        ),
        migrations.CreateModel(
            name='Estadocivil',
            fields=[
                ('idEstadoCivil', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Estadocivil',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Hechos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_carga', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=2000, null=True)),
                ('fecha_desde', models.DateTimeField()),
                ('fecha_hasta', models.DateTimeField()),
                ('fecha_esclarecido', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'hechos',
                'ordering': ['fecha_carga', 'preventivo'],
            },
        ),
        migrations.CreateModel(
            name='HechosDelito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('borrado', models.CharField(blank=True, max_length=1, null=True)),
                ('hechos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hechos', to='preventivos.Hechos')),
            ],
            options={
                'db_table': 'hechos_delito',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('idLocalidad', models.AutoField(primary_key=True, serialize=False)),
                ('idProvincia', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Localidad',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura', models.IntegerField(blank=True, default='0', null=True)),
                ('latitud', models.CharField(max_length=50)),
                ('longitud', models.CharField(max_length=50)),
                ('lote', models.CharField(blank=True, default='0', max_length=45, null=True)),
                ('manzana', models.CharField(blank=True, default='0', max_length=45, null=True)),
                ('sector', models.CharField(blank=True, default='', max_length=45, null=True)),
                ('departamento', models.CharField(blank=True, default='', max_length=45, null=True)),
                ('piso', models.CharField(blank=True, default='0', max_length=45, null=True)),
                ('nro_casa', models.IntegerField(blank=True, default='0', null=True)),
                ('edificio', models.CharField(blank=True, default='', max_length=45, null=True)),
                ('escalera', models.CharField(blank=True, default='', max_length=45, null=True)),
            ],
            options={
                'db_table': 'lugar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('idNacionalidad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'nacionalidad',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Padres',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('padre_nombres', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('padre_apellidos', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('padre_vive', models.BooleanField(default=True)),
                ('madre_apellidos', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('madre_nombres', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('madre_vive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'padres',
                'get_latest_by': 'id',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PersInvolucradas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('juridica', models.CharField(blank=True, choices=[('si', 'SI'), ('no', 'NO')], default='no', max_length=2)),
                ('razon_social', models.CharField(blank=True, max_length=150, null=True)),
                ('menor', models.CharField(blank=True, choices=[('si', 'SI'), ('no', 'NO')], default='no', max_length=2)),
                ('detenido', models.CharField(blank=True, choices=[('si', 'SI'), ('no', 'NO')], default='si', max_length=2)),
                ('tentativa', models.CharField(blank=True, choices=[('si', 'SI'), ('no', 'NO')], default='no', max_length=2)),
                ('infraganti', models.CharField(blank=True, choices=[('si', 'SI'), ('no', 'NO')], default='no', max_length=2)),
                ('fechahoradetencion', models.DateTimeField(blank=True, null=True)),
                ('fechahoralibertad', models.DateTimeField(blank=True, null=True)),
                ('cargado_prev', models.BooleanField(default=False)),
                ('nrocuit', models.CharField(default=0, max_length=11, unique=True)),
                ('ampliacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='preventivos.Ampliacion')),
            ],
            options={
                'db_table': 'persinvolucradas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('legajo', models.CharField(max_length=6)),
                ('credencial', models.IntegerField()),
                ('nro_cuenta_bco', models.CharField(max_length=20)),
                ('nro_seros', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'personal',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('apellidos', models.CharField(max_length=100, verbose_name='apellidos')),
                ('nombres', models.CharField(max_length=150, verbose_name='nombres')),
                ('nro_doc', models.CharField(max_length=50, unique=True)),
                ('cuit', models.CharField(blank=True, default=0, max_length=11, null=True)),
                ('celular', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nac', models.DateField()),
                ('alias', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'personas',
                'ordering': ['apellidos'],
            },
        ),
        migrations.CreateModel(
            name='Preventivos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nro', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999999)], verbose_name='Nro. :')),
                ('anio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2012), django.core.validators.MaxValueValidator(2025)], verbose_name='Año :')),
                ('caratula', models.CharField(max_length=250)),
                ('fecha_carga', models.DateTimeField(default=0)),
                ('fecha_denuncia', models.DateTimeField(default=0)),
                ('fecha_autorizacion', models.DateTimeField(null=True)),
                ('fecha_cierre', models.DateTimeField(null=True)),
                ('sendwebservice', models.IntegerField(default=0)),
                ('reenviado', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(null=True)),
                ('autoriza', models.CharField(blank=True, max_length=10, null=True)),
                ('aforo', models.IntegerField(null=True)),
                ('actuante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Actuante', to='preventivos.Actuantes', verbose_name='Actuante')),
            ],
            options={
                'db_table': 'preventivos',
                'ordering': ['nro', 'anio', 'dependencia'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('idProvincia', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'provincias',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='RefAutoridad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=300, verbose_name='e mail')),
            ],
            options={
                'db_table': 'ref_autoridad',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='RefBarrios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ref_barrios',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='RefCalles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'ref_calles',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='RefCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100, verbose_name='Ingrese Categoria :')),
            ],
            options={
                'db_table': 'ref_category',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='RefCiudades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=80)),
                ('lat', models.CharField(blank=True, max_length=50, null=True)),
                ('longi', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ref_ciudades',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='RefComunidades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(choices=[('1', 'Urbana'), ('2', 'Sub-urbana'), ('3', 'Rural'), ('4', 'Costa')], max_length=10)),
            ],
            options={
                'db_table': 'ref_comunidades',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='RefCondclimas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=150, unique=True)),
            ],
            options={
                'db_table': 'ref_condclimas',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='RefDelito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ref_delito',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='RefDepartamentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45, unique=True, verbose_name='Ingrese Departamento :')),
            ],
            options={
                'db_table': 'ref_departamentos',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='RefDivisionJerarquia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'ref_division_jerarquia',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='RefEstadosciv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(choices=[('0', 'NO REGISTRA'), ('1', 'SOLTERO'), ('2', 'CONCUBINO'), ('3', 'CASAD0'), ('4', 'DIVORCIADO'), ('5', 'VIUDO'), ('6', 'SEPARADO')], max_length=10)),
            ],
            options={
                'db_table': 'ref_estadociv',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='RefEstudios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(choices=[('1', 'PRIMARIO'), ('2', 'SECUNDARIO'), ('3', 'TERCIARIO'), ('4', 'UNIVERSITARIO')], max_length=13)),
            ],
            options={
                'db_table': 'ref_estudios',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='RefHogares',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'db_table': 'ref_hogares',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='RefItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'ref_items',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='RefJerarquias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
                ('ref_division_jerarquia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preventivos.RefDivisionJerarquia')),
            ],
            options={
                'db_table': 'ref_jerarquias',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='RefLugares',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'db_table': 'ref_lugares',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='RefModosHecho',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=80)),
                ('delito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preventivos.RefDelito')),
            ],
            options={
                'db_table': 'ref_modos_hecho',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RefMotivosHecho',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'ref_motivos_hecho',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RefOcupacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'ref_ocupacion',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='RefPaises',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45, unique=True, verbose_name='Seleccione Pais :')),
            ],
            options={
                'db_table': 'ref_paises',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='RefPeople',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150, unique=True, verbose_name='Involucrados - Tipos :')),
            ],
            options={
                'db_table': 'ref_people',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='RefProvincia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45, verbose_name='Ingrese Provincia :')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preventivos.RefPaises')),
            ],
            options={
                'db_table': 'ref_provincia',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='RefSexo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(choices=[('1', 'Femenino'), ('2', 'Masculino')], max_length=10)),
            ],
            options={
                'db_table': 'ref_sexo',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='RefSistemadis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'ref_sistemadis',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='RefSubtiposa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100, verbose_name='Ingrese Sub-Tipo :')),
            ],
            options={
                'db_table': 'ref_subtiposa',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='RefTipoDelitos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ref_tipo_delito',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='RefTipoDocumento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(choices=[('1', 'DNI'), ('2', 'LC'), ('3', 'LE'), ('4', 'CI'), ('5', 'PAS'), ('6', 'NO POSEE')], max_length=8)),
            ],
            options={
                'db_table': 'ref_tipodocumento',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='RefTipodrogas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(choices=[('1', 'Marihuana'), ('2', 'Cocaina'), ('3', 'Inhalantes'), ('4', 'Paco'), ('5', 'Energizantes'), ('6', 'Extasis'), ('7', 'Otros')], max_length=50)),
            ],
            options={
                'db_table': 'reftipodrogas',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='RefTipoelementos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(choices=[('1', 'DENUNCIADOS'), ('2', 'SECUESTRADOS'), ('3', 'UTILIZADOS'), ('4', 'UTILIZADOS/SECUESTRADOS')], max_length=50)),
            ],
            options={
                'db_table': 'reftipoelementos',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='RefTipoJerarquia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'ref_tipo_jerarquia',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='RefTiposarmas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'ref_tiposarmas',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='RefTrademark',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'ref_trademark',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='RefUnidadmedidas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'refunidadmedidas',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Registrouser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('tablas', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Registrouser',
            },
        ),
        migrations.CreateModel(
            name='RolPersonas',
            fields=[
                ('idRolPersonas', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'rolpersonas',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Tipodocumentos',
            fields=[
                ('idtipodocumento', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'Tipodocumentos',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TipoOcupacion',
            fields=[
                ('idtipoocupacion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tipocupacion',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='UnidadesRegionales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=80)),
                ('cabecera_envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='preventivos.Dependencias')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preventivos.RefCiudades')),
            ],
            options={
                'db_table': 'unidades_regionales',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.BooleanField(default=True)),
                ('ultimo_ingreso', models.DateTimeField(blank=True, null=True)),
                ('solicitud_cambio', models.BooleanField(default=False)),
                ('fecha_solicitud', models.DateTimeField(blank=True, null=True)),
                ('clave_anterior', models.CharField(blank=True, max_length=128, null=True)),
                ('depe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='preventivos.Dependencias')),
                ('ureg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='preventivos.UnidadesRegionales')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserProfile',
            },
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dominio', models.CharField(blank=True, max_length=10, null=True)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('nmotor', models.CharField(blank=True, max_length=100, null=True)),
                ('nchasis', models.CharField(blank=True, max_length=100, null=True)),
                ('tipov', models.CharField(max_length=20)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_carga', models.DateTimeField(auto_now=True)),
                ('nro_doc', models.IntegerField(blank=True, null=True)),
                ('propietario', models.CharField(blank=True, max_length=100, null=True)),
                ('idmarca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='preventivos.RefTrademark')),
            ],
            options={
                'db_table': 'vehiculos',
                'ordering': ['dominio'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='refunidadmedidas',
            unique_together={('descripcion',)},
        ),
        migrations.AddField(
            model_name='refsubtiposa',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tiposub', to='preventivos.RefTiposarmas'),
        ),
        migrations.AlterUniqueTogether(
            name='refsistemadis',
            unique_together={('descripcion',)},
        ),
        migrations.AddField(
            model_name='refjerarquias',
            name='ref_tipo_jerarquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preventivos.RefTipoJerarquia'),
        ),
        migrations.AddField(
            model_name='refdepartamentos',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preventivos.RefProvincia'),
        ),
        migrations.AddField(
            model_name='refdelito',
            name='tipo_delito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preventivos.RefTipoDelitos'),
        ),
        migrations.AddField(
            model_name='refciudades',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='preventivos.RefDepartamentos'),
        ),
        migrations.AddField(
            model_name='refciudades',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preventivos.RefPaises'),
        ),
        migrations.AddField(
            model_name='refciudades',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='preventivos.RefProvincia'),
        ),
        migrations.AddField(
            model_name='refcategory',
            name='rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rubcategory', to='preventivos.RefItems'),
        ),
        migrations.AddField(
            model_name='refcalles',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ciucalle', to='preventivos.RefCiudades'),
        ),
        migrations.AddField(
            model_name='refbarrios',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preventivos.RefCiudades'),
        ),
        migrations.AddField(
            model_name='refautoridad',
            name='ciudades',
            field=models.ManyToManyField(blank=True, related_name='ciu_autori', to='preventivos.RefCiudades'),
        ),
        migrations.AddField(
            model_name='preventivos',
            name='autoridades',
            field=models.ManyToManyField(blank=True, to='preventivos.RefAutoridad'),
        ),
        migrations.AddField(
            model_name='preventivos',
            name='dependencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='preventivos.Dependencias'),
        ),
        migrations.AddField(
            model_name='preventivos',
            name='preventor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Preventor', to='preventivos.Actuantes', verbose_name='Preventor'),
        ),
        migrations.AddField(
            model_name='personas',
            name='ciudad_nac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ciudad_nac', to='preventivos.RefCiudades'),
        ),
        migrations.AddField(
            model_name='personas',
            name='ciudad_res',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ciudad_res', to='preventivos.RefCiudades'),
        ),
        migrations.AddField(
            model_name='personas',
            name='estado_civil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='preventivos.RefEstadosciv'),
        ),
        migrations.AddField(
            model_name='personas',
            name='ocupacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='preventivos.RefOcupacion'),
        ),
        migrations.AddField(
            model_name='personas',
            name='pais_nac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pais_nac', to='preventivos.RefPaises'),
        ),
        migrations.AddField(
            model_name='personas',
            name='sexo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preventivos.RefSexo'),
        ),
        migrations.AddField(
            model_name='personas',
            name='tipo_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preventivos.RefTipoDocumento', verbose_name='tipo documento'),
        ),
        migrations.AddField(
            model_name='personal',
            name='persona_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='preventivos.Personas'),
        ),
        migrations.AddField(
            model_name='persinvolucradas',
            name='cuit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='preventivos.RefTipoDocumento', verbose_name='cuit'),
        ),
        migrations.AddField(
            model_name='persinvolucradas',
            name='hechos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='involu', to='preventivos.Hechos'),
        ),
        migrations.AddField(
            model_name='persinvolucradas',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='perso', to='preventivos.Personas'),
        ),
        migrations.AddField(
            model_name='persinvolucradas',
            name='roles',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rol', to='preventivos.RefPeople'),
        ),
        migrations.AddField(
            model_name='padres',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='padre', to='preventivos.Personas'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='barrio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='preventivos.RefBarrios'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='calle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calle_hecho', to='preventivos.RefCalles'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='cond_climaticas',
            field=models.ManyToManyField(blank=True, related_name='condiciones', to='preventivos.RefCondclimas'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='delito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='preventivos.RefDelito'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='dependencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='preventivos.Dependencias'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='hecho',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lugar_hecho', to='preventivos.Hechos'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='tipo_lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preventivos.RefLugares'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preventivos.RefComunidades'),
        ),
        migrations.AddField(
            model_name='hechosdelito',
            name='refdelito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='delis', to='preventivos.RefDelito'),
        ),
        migrations.AddField(
            model_name='hechosdelito',
            name='refmodoshecho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modus', to='preventivos.RefModosHecho'),
        ),
        migrations.AddField(
            model_name='hechos',
            name='motivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preventivos.RefMotivosHecho'),
        ),
        migrations.AddField(
            model_name='hechos',
            name='preventivo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='hecho', to='preventivos.Preventivos'),
        ),
        migrations.AddField(
            model_name='envioprejudicial',
            name='preventivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='preventivos.Preventivos'),
        ),
        migrations.AddField(
            model_name='envioprejudicial',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='elementoscars',
            name='idvehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='preventivos.Vehiculos'),
        ),
        migrations.AddField(
            model_name='elementos',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preventivos.RefCategory'),
        ),
        migrations.AddField(
            model_name='elementos',
            name='hechos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eleinvolu', to='preventivos.Hechos'),
        ),
        migrations.AddField(
            model_name='elementos',
            name='rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preventivos.RefItems'),
        ),
        migrations.AddField(
            model_name='elementos',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preventivos.RefTipoelementos'),
        ),
        migrations.AddField(
            model_name='elementos',
            name='unidadmed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preventivos.RefUnidadmedidas'),
        ),
        migrations.AddField(
            model_name='drogas',
            name='idtipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='preventivos.RefTipodrogas'),
        ),
        migrations.AddField(
            model_name='domicilios',
            name='barrio_codigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='preventivos.RefBarrios'),
        ),
        migrations.AddField(
            model_name='domicilios',
            name='calle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='domicilio', to='preventivos.RefCalles'),
        ),
        migrations.AddField(
            model_name='domicilios',
            name='entre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='interseccion', to='preventivos.RefCalles'),
        ),
        migrations.AddField(
            model_name='domicilios',
            name='personas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='persodom', to='preventivos.Personas'),
        ),
        migrations.AddField(
            model_name='domicilios',
            name='ref_ciudades',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='preventivos.RefCiudades'),
        ),
        migrations.AddField(
            model_name='domicilios',
            name='ref_zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='preventivos.RefComunidades'),
        ),
        migrations.AddField(
            model_name='domicilios',
            name='tipos_domicilio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='preventivos.RefHogares'),
        ),
        migrations.AddField(
            model_name='detenidos',
            name='hechos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='preventivos.Hechos'),
        ),
        migrations.AddField(
            model_name='detenidos',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='preventivos.Personas'),
        ),
        migrations.AddField(
            model_name='dependencias',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preventivos.RefCiudades'),
        ),
        migrations.AddField(
            model_name='dependencias',
            name='unidades_regionales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='preventivos.UnidadesRegionales'),
        ),
        migrations.AddField(
            model_name='armas',
            name='marcas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='preventivos.RefTrademark'),
        ),
        migrations.AddField(
            model_name='armas',
            name='sistema_disparo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='preventivos.RefSistemadis'),
        ),
        migrations.AddField(
            model_name='armas',
            name='subtipos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preventivos.RefSubtiposa'),
        ),
        migrations.AddField(
            model_name='armas',
            name='tipos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preventivos.RefTiposarmas'),
        ),
        migrations.AddField(
            model_name='ampliacion',
            name='autoridades',
            field=models.ManyToManyField(blank=True, to='preventivos.RefAutoridad'),
        ),
        migrations.AddField(
            model_name='ampliacion',
            name='preventivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ampli', to='preventivos.Preventivos'),
        ),
        migrations.AddField(
            model_name='actuantes',
            name='dependencia_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preventivos.Dependencias'),
        ),
        migrations.AddField(
            model_name='actuantes',
            name='jerarquia_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preventivos.RefJerarquias'),
        ),
        migrations.AddField(
            model_name='actuantes',
            name='persona_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preventivos.Personas'),
        ),
        migrations.AddField(
            model_name='actuantes',
            name='unidadreg_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preventivos.UnidadesRegionales'),
        ),
        migrations.AlterUniqueTogether(
            name='unidadesregionales',
            unique_together={('descripcion', 'ciudad')},
        ),
        migrations.AlterUniqueTogether(
            name='refsubtiposa',
            unique_together={('descripcion', 'tipo')},
        ),
        migrations.AlterUniqueTogether(
            name='refprovincia',
            unique_together={('descripcion', 'pais')},
        ),
        migrations.AlterUniqueTogether(
            name='refmodoshecho',
            unique_together={('descripcion', 'delito')},
        ),
        migrations.AlterUniqueTogether(
            name='refdelito',
            unique_together={('descripcion', 'tipo_delito')},
        ),
        migrations.AlterUniqueTogether(
            name='refciudades',
            unique_together={('pais', 'provincia', 'departamento', 'descripcion')},
        ),
        migrations.AlterUniqueTogether(
            name='refcategory',
            unique_together={('descripcion', 'rubro')},
        ),
        migrations.AlterUniqueTogether(
            name='refcalles',
            unique_together={('descripcion', 'ciudad')},
        ),
        migrations.AlterUniqueTogether(
            name='refbarrios',
            unique_together={('descripcion', 'ciudad')},
        ),
        migrations.AlterUniqueTogether(
            name='personas',
            unique_together={('tipo_doc', 'nro_doc', 'apellidos', 'nombres')},
        ),
        migrations.AlterUniqueTogether(
            name='persinvolucradas',
            unique_together={('hechos', 'persona', 'roles', 'cargado_prev', 'ampliacion')},
        ),
        migrations.AlterUniqueTogether(
            name='padres',
            unique_together={('persona', 'padre_nombres', 'padre_apellidos', 'madre_nombres', 'madre_apellidos')},
        ),
        migrations.AlterUniqueTogether(
            name='hechosdelito',
            unique_together={('hechos', 'refdelito', 'refmodoshecho')},
        ),
        migrations.AlterUniqueTogether(
            name='domicilios',
            unique_together={('personas', 'ref_ciudades', 'barrio_codigo', 'fecha_desde', 'calle', 'altura')},
        ),
        migrations.AlterUniqueTogether(
            name='detenidos',
            unique_together={('hechos', 'persona')},
        ),
        migrations.AlterUniqueTogether(
            name='dependencias',
            unique_together={('descripcion', 'unidades_regionales', 'ciudad')},
        ),
    ]
