# Generated by Django 2.0.2 on 2018-12-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preventivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='refciudades',
            unique_together={('pais', 'provincia', 'descripcion')},
        ),
    ]
