# Generated by Django 2.0.2 on 2019-01-30 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preventivos', '0003_add_temp_fields_change_meta_domiciliios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domicilios',
            name='fecha_desde',
        ),
        migrations.RemoveField(
            model_name='domicilios',
            name='fecha_hasta',
        ),
    ]
