# Generated by Django 2.0.2 on 2019-01-30 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preventivos', '0005_rename_temp_fields_domicilios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domicilios',
            options={'get_latest_by': 'id', 'ordering': ['-fecha_desde']},
        ),
        migrations.AlterUniqueTogether(
            name='domicilios',
            unique_together={('personas', 'ref_ciudades', 'barrio_codigo', 'fecha_desde', 'calle', 'altura')},
        ),
    ]
