# Generated by Django 2.0.2 on 2019-01-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventivos', '0006_add_meta_domicilios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilios',
            name='fecha_desde',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='domicilios',
            name='fecha_hasta',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
